=== Opticos/GWSL-Source/src/gwsl/VCXSRV/xkbdata/rules/xkb.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--

  Description: XKB configuration file DTD
  Author: Sergey V. Udaltsov

-->

<!ELEMENT xkbConfigRegistry (modelList,layoutList,optionList)>

<!ATTLIST xkbConfigRegistry 
          version CDATA "1.1">

<!ELEMENT modelList (model*)>

<!ELEMENT model (configItem)>

<!ELEMENT layoutList (layout*)>

<!ELEMENT layout (configItem,variantList?)>

<!ELEMENT optionList (group*)>

<!ELEMENT variantList (variant*)>

<!ELEMENT variant (configItem)>

<!ELEMENT group (configItem,option*)>
<!ATTLIST group
          allowMultipleSelection (true|false) "false">

<!ELEMENT option (configItem)>

<!ELEMENT configItem (name,shortDescription*,description*,vendor?,countryList?,languageList?,hwList?)>

<!ATTLIST configItem
          popularity (standard|exotic) "standard">

<!ELEMENT name (#PCDATA)>

<!ELEMENT shortDescription (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT vendor (#PCDATA)>

<!ELEMENT countryList (iso3166Id+)>

<!ELEMENT iso3166Id (#PCDATA)>

<!ELEMENT languageList (iso639Id+)>

<!ELEMENT iso639Id (#PCDATA)>

<!ELEMENT hwList (hwId+)>

<!ELEMENT hwId (#PCDATA)>

=== Opticos/GWSL-Source/src/gwsl/VCXSRV/xkbdata/rules/base.extras.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xkbConfigRegistry SYSTEM "xkb.dtd">
<xkbConfigRegistry>
  <modelList/>
  <layoutList>
    <layout>
      <configItem>
        <name>apl</name>
        <shortDescription>apl</shortDescription>
        <description>APL</description>
        <languageList>
          <iso639Id>eng</iso639Id>
        </languageList>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>dyalog</name>
            <shortDescription>dlg</shortDescription>
            <description>Dyalog APL complete</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>sax</name>
            <shortDescription>sax</shortDescription>
            <description>APL Keyboard Symbols: sax</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>unified</name>
            <shortDescription>ufd</shortDescription>
            <description>APL Keyboard Symbols: Unified Layout</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>apl2</name>
            <shortDescription>apl2</shortDescription>
            <description>APL Keyboard Symbols: IBM APL2</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>aplplusII</name>
            <shortDescription>aplII</shortDescription>
            <description>APL Keyboard Symbols: Manugistics APL*PLUS II</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>aplx</name>
            <shortDescription>aplx</shortDescription>
            <description>APL Keyboard Symbols: APLX Unified APL Layout</description>
          </configItem>
        </variant>
      </variantList>
    </layout>
    <layout>
      <configItem>
        <name>ca</name>
        <shortDescription>fr</shortDescription>
        <description>French (Canada)</description>
        <languageList>
          <iso639Id>fra</iso639Id>
        </languageList>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>kut</name>
            <shortDescription>kut</shortDescription>
            <description>Kutenai</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>shs</name>
            <shortDescription>shs</shortDescription>
            <description>Secwepemctsin</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>sun_type6</name>
            <description>Multilingual (Canada, Sun Type 6/7)</description>
          </configItem>
        </variant>
      </variantList>
    </layout>
    <layout>
      <configItem>
        <name>de</name>
        <shortDescription>de</shortDescription>
        <description>German</description>
        <languageList>
          <iso639Id>ger</iso639Id>
        </languageList>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>us</name>
            <description>German (US, with German letters)</description>
            <languageList>
              <iso639Id>eng</iso639Id>
            </languageList>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>hu</name>
            <description>German (with Hungarian letters and no dead keys)</description>
            <languageList>
              <iso639Id>ger</iso639Id>
              <iso639Id>hun</iso639Id>
            </languageList>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>pl</name>
            <description>Polish (Germany, no dead keys)</description>
            <languageList>
              <iso639Id>ger</iso639Id>
              <iso639Id>pol</iso639Id>
            </languageList>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>sun_type6</name>
            <description>German (Sun Type 6/7)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>adnw</name>
            <description>German (Aus der Neo-Welt)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>koy</name>
            <description>German (KOY)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>bone</name>
            <description>German (Bone)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>bone_eszett_home</name>
            <description>German (Bone, eszett home row)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>neo_qwertz</name>
            <description>German (Neo qwertz)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>neo_qwerty</name>
            <description>German (Neo qwerty)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>ru-recom</name>
            <!-- Keyboard indicator for Russian layouts -->
            <shortDescription>ru</shortDescription>
            <description>Russian (Germany, recommended)</description>
            <languageList>
              <iso639Id>rus</iso639Id>
            </languageList>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>ru-translit</name>
            <!-- Keyboard indicator for Russian layouts -->
            <shortDescription>ru</shortDescription>
            <description>Russian (Germany, transliteration)</description>
            <languageList>
              <iso639Id>rus</iso639Id>
            </languageList>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>lld</name>
            <shortDescription>de_lld</shortDescription>
            <description>German Ladin</description>
            <languageList>
              <iso639Id>ger</iso639Id>
              <iso639Id>lld</iso639Id>
            </languageList>
          </configItem>
        </variant>
      </variantList>
    </layout>
    <layout>
      <configItem>
        <name>hu</name>
        <description>Hungarian</description>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>oldhun</name>
            <shortDescription>oldhun</shortDescription>
            <description>Old Hungarian</description>
          </configItem>
        </variant>
      </variantList>
    </layout>
    <layout>
      <configItem>
        <name>ir</name>
        <shortDescription>fa</shortDescription>
        <description>Persian</description>
        <languageList>
          <iso639Id>per</iso639Id>
        </languageList>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>ave</name>
            <description>Avestan</description>
            <languageList>
              <iso639Id>ave</iso639Id>
            </languageList>
          </configItem>
        </variant>
      </variantList>
    </layout>
    <layout>
      <configItem>
        <name>lt</name>
        <shortDescription>lt</shortDescription>
        <description>Lithuanian</description>
        <languageList>
          <iso639Id>lit</iso639Id>
        </languageList>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>us_dvorak</name>
            <description>Lithuanian (US Dvorak with Lithuanian letters)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>sun_type6</name>
            <description>Lithuanian (Sun Type 6/7)</description>
          </configItem>
        </variant>
      </variantList>
    </layout>
    <layout>
      <configItem>
        <name>lv</name>
        <shortDescription>lv</shortDescription>
        <description>Latvian</description>
        <languageList>
          <iso639Id>lav</iso639Id>
        </languageList>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>dvorak</name>
            <description>Latvian (US Dvorak)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>ykeydvorak</name>
            <description>Latvian (US Dvorak, Y variant)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>minuskeydvorak</name>
            <description>Latvian (US Dvorak, minus variant)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>dvorakprogr</name>
            <description>Latvian (programmer US Dvorak)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>ykeydvorakprogr</name>
            <description>Latvian (programmer US Dvorak, Y variant)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>minuskeydvorakprogr</name>
            <description>Latvian (programmer US Dvorak, minus variant)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>colemak</name>
            <description>Latvian (US Colemak)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>apostrophecolemak</name>
            <description>Latvian (US Colemak, apostrophe variant)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
